package core

import (
	. "github.com/onsi/ginkgo/v2/dsl/core"
	. "github.com/onsi/gomega"
)

var _ = Describe("UndoManager internals test", func() {
	var uOfD *UniverseOfDiscourse
	var trans *Transaction

	BeforeEach(func() {
		uOfD = NewUniverseOfDiscourse()
		trans = uOfD.NewTransaction()
	})

	AfterEach(func() {
		trans.ReleaseLocks()
	})

	Describe("Test undo redo on empty stack", func() {
		Specify("Turn undo recording on and off should work", func() {
			uOfD.SetRecordingUndo(true)
			Expect(uOfD.IsRecordingUndo()).To(BeTrue())
			uOfD.SetRecordingUndo(false)
			Expect(uOfD.IsRecordingUndo()).To(BeFalse())
		})
		Specify("Performing undo and redo on empty stack should not break anything", func() {
			uOfD.SetRecordingUndo(true)
			Expect(uOfD.IsRecordingUndo()).To(BeTrue())
			uOfD.Undo(trans)
			uOfD.Redo(trans)
			uOfD.SetRecordingUndo(false)
			Expect(uOfD.IsRecordingUndo()).To(BeFalse())
		})
	})

	Describe("Test Creation Undo and Redo", func() {
		Specify("Undo of Element creation should work", func() {
			uOfD.SetRecordingUndo(true)
			el, _ := uOfD.NewElement(trans)
			Expect(uOfD.GetElement(el.getConceptIDNoLock())).To(Equal(el))
			uOfD.Undo(trans)
			Expect(uOfD.GetElement(el.getConceptIDNoLock())).To(BeNil())
			uOfD.Redo(trans)
			Expect(uOfD.GetElement(el.getConceptIDNoLock())).To(Equal(el))
		})
		Specify("Undo of Literal creation should work", func() {
			uOfD.SetRecordingUndo(true)
			lit, _ := uOfD.NewLiteral(trans)
			Expect(uOfD.GetLiteral(lit.getConceptIDNoLock())).To(Equal(lit))
			uOfD.Undo(trans)
			Expect(uOfD.GetLiteral(lit.getConceptIDNoLock())).To(BeNil())
			uOfD.Redo(trans)
			Expect(uOfD.GetLiteral(lit.getConceptIDNoLock())).To(Equal(lit))
		})
		Specify("Undo of Reference creation should work", func() {
			uOfD.SetRecordingUndo(true)
			ref, _ := uOfD.NewReference(trans)
			Expect(uOfD.GetReference(ref.getConceptIDNoLock())).To(Equal(ref))
			uOfD.Undo(trans)
			Expect(uOfD.GetReference(ref.getConceptIDNoLock())).To(BeNil())
			uOfD.Redo(trans)
			Expect(uOfD.GetReference(ref.getConceptIDNoLock())).To(Equal(ref))
		})
		Specify("Undo of Refinement creation should work", func() {
			uOfD.SetRecordingUndo(true)
			ref, _ := uOfD.NewRefinement(trans)
			Expect(uOfD.GetRefinement(ref.getConceptIDNoLock())).To(Equal(ref))
			uOfD.Undo(trans)
			Expect(uOfD.GetRefinement(ref.getConceptIDNoLock())).To(BeNil())
			uOfD.Redo(trans)
			Expect(uOfD.GetRefinement(ref.getConceptIDNoLock())).To(Equal(ref))
		})
		Specify("Undo of Element and owned Literal creation should work", func() {
			uOfD.SetRecordingUndo(true)
			el, _ := uOfD.NewElement(trans)
			Expect(uOfD.GetElement(el.getConceptIDNoLock())).To(Equal(el))
			lit, _ := uOfD.NewOwnedLiteral(el, "literal1", trans)
			Expect(uOfD.GetLiteral(lit.getConceptIDNoLock())).ToNot(BeNil())
			Expect(uOfD.GetLiteral(lit.getConceptIDNoLock())).To(Equal(lit))
			Expect(uOfD.ownedIDsMap.ContainsMappedValue(el.getConceptIDNoLock(), lit.getConceptIDNoLock())).To(BeTrue())
			uOfD.Undo(trans)
			Expect(uOfD.GetElement(el.getConceptIDNoLock())).To(BeNil())
			Expect(uOfD.GetLiteral(lit.getConceptIDNoLock())).To(BeNil())
			Expect(uOfD.ownedIDsMap.ContainsMappedValue(el.getConceptIDNoLock(), lit.getConceptIDNoLock())).To(BeFalse())
			uOfD.Redo(trans)
			Expect(uOfD.GetElement(el.getConceptIDNoLock())).To(Equal(el))
			Expect(uOfD.GetLiteral(lit.getConceptIDNoLock())).To(Equal(lit))
			Expect(uOfD.ownedIDsMap.ContainsMappedValue(el.getConceptIDNoLock(), lit.getConceptIDNoLock())).To(BeTrue())
		})
	})

	Describe("Test Undo of setting non-pointer values", func() {
		Specify("Undo of SetDefinition should work", func() {
			el, _ := uOfD.NewElement(trans)
			uOfD.SetRecordingUndo(true)
			value := "Test"
			el.SetDefinition(value, trans)
			Expect(el.GetDefinition(trans)).To(Equal(value))
			uOfD.Undo(trans)
			Expect(el.GetDefinition(trans)).To(Equal(""))
			uOfD.Redo(trans)
			Expect(el.GetDefinition(trans)).To(Equal(value))
		})
		Specify("Undo of SetLabel should work", func() {
			el, _ := uOfD.NewElement(trans)
			uOfD.SetRecordingUndo(true)
			value := "Test"
			el.SetLabel(value, trans)
			Expect(el.GetLabel(trans)).To(Equal(value))
			uOfD.Undo(trans)
			Expect(el.GetLabel(trans)).To(Equal(""))
			uOfD.Redo(trans)
			Expect(el.GetLabel(trans)).To(Equal(value))
		})
		Specify("Undo of setIsCore should work", func() {
			el, _ := uOfD.NewElement(trans)
			uOfD.SetRecordingUndo(true)
			el.SetIsCore(trans)
			Expect(el.GetIsCore(trans)).To(BeTrue())
			uOfD.Undo(trans)
			Expect(el.GetIsCore(trans)).To(BeFalse())
			uOfD.Redo(trans)
			Expect(el.GetIsCore(trans)).To(BeTrue())
		})
		Specify("Undo of SetReadOnly should work", func() {
			el, _ := uOfD.NewElement(trans)
			uOfD.SetRecordingUndo(true)
			el.SetReadOnly(true, trans)
			Expect(el.IsReadOnly(trans)).To(BeTrue())
			uOfD.Undo(trans)
			Expect(el.IsReadOnly(trans)).To(BeFalse())
			uOfD.Redo(trans)
			Expect(el.IsReadOnly(trans)).To(BeTrue())
		})
		Specify("Undo of SetURI should work", func() {
			el, _ := uOfD.NewElement(trans)
			uOfD.SetRecordingUndo(true)
			uri := "http://test.uri"
			el.SetURI(uri, trans)
			Expect(el.GetURI(trans)).To(Equal(uri))
			uOfD.Undo(trans)
			Expect(el.GetURI(trans)).To(Equal(""))
			uOfD.Redo(trans)
			Expect(el.GetURI(trans)).To(Equal(uri))
		})
		Specify("Undo of SetLiteralValue should work", func() {
			lit, _ := uOfD.NewLiteral(trans)
			uOfD.SetRecordingUndo(true)
			value := "Literal Value"
			lit.SetLiteralValue(value, trans)
			Expect(lit.GetLiteralValue(trans)).To(Equal(value))
			uOfD.Undo(trans)
			Expect(lit.GetLiteralValue(trans)).To(Equal(""))
			uOfD.Redo(trans)
			Expect(lit.GetLiteralValue(trans)).To(Equal(value))
		})
	})

	Describe("Test undo of setting pointer-related values", func() {
		Specify("Undo of SetOwningConceptID should work", func() {
			el, _ := uOfD.NewElement(trans)
			owner, _ := uOfD.NewElement(trans)
			uOfD.SetRecordingUndo(true)
			el.SetOwningConceptID(owner.getConceptIDNoLock(), trans)
			Expect(el.GetOwningConceptID(trans)).To(Equal(owner.getConceptIDNoLock()))
			Expect(el.GetOwningConcept(trans)).To(Equal(owner))
			Expect(uOfD.GetConceptsOwnedConceptIDs(owner.GetConceptID(trans)).Contains(el.getConceptIDNoLock())).To(BeTrue())
			uOfD.Undo(trans)
			Expect(el.GetOwningConceptID(trans)).To(Equal(""))
			Expect(el.GetOwningConcept(trans)).To(BeNil())
			Expect(uOfD.GetConceptsOwnedConceptIDs(owner.GetConceptID(trans)).Contains(el.getConceptIDNoLock())).To(BeFalse())
			uOfD.Redo(trans)
			Expect(el.GetOwningConceptID(trans)).To(Equal(owner.getConceptIDNoLock()))
			Expect(el.GetOwningConcept(trans)).To(Equal(owner))
			Expect(uOfD.GetConceptsOwnedConceptIDs(owner.GetConceptID(trans)).Contains(el.getConceptIDNoLock())).To(BeTrue())
		})
		Specify("Undo of SetReferencedConceptID should work", func() {
			ref, _ := uOfD.NewReference(trans)
			target, _ := uOfD.NewElement(trans)
			uOfD.SetRecordingUndo(true)
			ref.SetReferencedConceptID(target.getConceptIDNoLock(), NoAttribute, trans)
			Expect(ref.GetReferencedConceptID(trans)).To(Equal(target.getConceptIDNoLock()))
			Expect(ref.GetReferencedConcept(trans)).To(Equal(target))
			Expect(uOfD.GetListenerIDs(target.GetConceptID(trans)).Contains(ref.getConceptIDNoLock())).To(BeTrue())
			uOfD.Undo(trans)
			Expect(ref.GetReferencedConceptID(trans)).To(Equal(""))
			Expect(ref.GetReferencedConcept(trans)).To(BeNil())
			Expect(uOfD.GetListenerIDs(target.GetConceptID(trans)).Contains(ref.getConceptIDNoLock())).To(BeFalse())
			uOfD.Redo(trans)
			Expect(ref.GetReferencedConceptID(trans)).To(Equal(target.getConceptIDNoLock()))
			Expect(ref.GetReferencedConcept(trans)).To(Equal(target))
			Expect(uOfD.GetListenerIDs(target.GetConceptID(trans)).Contains(ref.getConceptIDNoLock())).To(BeTrue())
		})
		Specify("Undo of SetAbstractConceptID should work", func() {
			ref, _ := uOfD.NewRefinement(trans)
			target, _ := uOfD.NewElement(trans)
			uOfD.SetRecordingUndo(true)
			ref.SetAbstractConceptID(target.getConceptIDNoLock(), trans)
			Expect(ref.GetAbstractConceptID(trans)).To(Equal(target.getConceptIDNoLock()))
			Expect(ref.GetAbstractConcept(trans)).To(Equal(target))
			Expect(uOfD.GetListenerIDs(target.GetConceptID(trans)).Contains(ref.getConceptIDNoLock())).To(BeTrue())
			uOfD.Undo(trans)
			Expect(ref.GetAbstractConceptID(trans)).To(Equal(""))
			Expect(ref.GetAbstractConcept(trans)).To(BeNil())
			Expect(uOfD.GetListenerIDs(target.GetConceptID(trans)).Contains(ref.getConceptIDNoLock())).To(BeFalse())
			uOfD.Redo(trans)
			Expect(ref.GetAbstractConceptID(trans)).To(Equal(target.getConceptIDNoLock()))
			Expect(ref.GetAbstractConcept(trans)).To(Equal(target))
			Expect(uOfD.GetListenerIDs(target.GetConceptID(trans)).Contains(ref.getConceptIDNoLock())).To(BeTrue())
		})
		Specify("Undo of SetRefinedConceptID should work", func() {
			ref, _ := uOfD.NewRefinement(trans)
			target, _ := uOfD.NewElement(trans)
			uOfD.SetRecordingUndo(true)
			ref.SetRefinedConceptID(target.getConceptIDNoLock(), trans)
			Expect(ref.GetRefinedConceptID(trans)).To(Equal(target.getConceptIDNoLock()))
			Expect(ref.GetRefinedConcept(trans)).To(Equal(target))
			Expect(uOfD.GetListenerIDs(target.GetConceptID(trans)).Contains(ref.getConceptIDNoLock())).To(BeTrue())
			uOfD.Undo(trans)
			Expect(ref.GetRefinedConceptID(trans)).To(Equal(""))
			Expect(ref.GetRefinedConcept(trans)).To(BeNil())
			Expect(uOfD.GetListenerIDs(target.GetConceptID(trans)).Contains(ref.getConceptIDNoLock())).To(BeFalse())
			uOfD.Redo(trans)
			Expect(ref.GetRefinedConceptID(trans)).To(Equal(target.getConceptIDNoLock()))
			Expect(ref.GetRefinedConcept(trans)).To(Equal(target))
			Expect(uOfD.GetListenerIDs(target.GetConceptID(trans)).Contains(ref.getConceptIDNoLock())).To(BeTrue())
		})
	})
	Describe("Test restoration of owned elements", func() {
		Specify("When child deletion is undone/redone", func() {
			uOfD.SetRecordingUndo(true)
			parent, _ := uOfD.NewElement(trans)
			parent.SetLabel("Parent", trans)
			child, _ := uOfD.NewElement(trans)
			child.SetLabel("Child", trans)
			child.SetOwningConcept(parent, trans)
			uOfD.MarkUndoPoint()
			Expect(uOfD.GetConceptsOwnedConceptIDs(parent.GetConceptID(trans)).Contains(child.getConceptIDNoLock())).To(BeTrue())
			uOfD.DeleteElement(child, trans)
			Expect(uOfD.GetConceptsOwnedConceptIDs(parent.GetConceptID(trans)).Contains(child.getConceptIDNoLock())).To(BeFalse())
			uOfD.Undo(trans)
			Expect(uOfD.GetConceptsOwnedConceptIDs(parent.GetConceptID(trans)).Contains(child.getConceptIDNoLock())).To(BeTrue())
			uOfD.Redo(trans)
			Expect(uOfD.GetConceptsOwnedConceptIDs(parent.GetConceptID(trans)).Contains(child.getConceptIDNoLock())).To(BeFalse())
		})
		Specify("When child's ownership changes", func() {
			parent1, _ := uOfD.NewElement(trans)
			parent2, _ := uOfD.NewElement(trans)
			child, _ := uOfD.NewElement(trans)
			child.SetOwningConcept(parent1, trans)
			Expect(uOfD.GetConceptsOwnedConceptIDs(parent1.GetConceptID(trans)).Contains(child.getConceptIDNoLock())).To(BeTrue())
			Expect(uOfD.GetConceptsOwnedConceptIDs(parent2.GetConceptID(trans)).Contains(child.getConceptIDNoLock())).To(BeFalse())
			uOfD.SetRecordingUndo(true)
			child.SetOwningConcept(parent2, trans)
			Expect(uOfD.GetConceptsOwnedConceptIDs(parent1.GetConceptID(trans)).Contains(child.getConceptIDNoLock())).To(BeFalse())
			Expect(uOfD.GetConceptsOwnedConceptIDs(parent2.GetConceptID(trans)).Contains(child.getConceptIDNoLock())).To(BeTrue())
			uOfD.Undo(trans)
			Expect(uOfD.GetConceptsOwnedConceptIDs(parent1.GetConceptID(trans)).Contains(child.getConceptIDNoLock())).To(BeTrue())
			Expect(uOfD.GetConceptsOwnedConceptIDs(parent2.GetConceptID(trans)).Contains(child.getConceptIDNoLock())).To(BeFalse())
			uOfD.Redo(trans)
			Expect(uOfD.GetConceptsOwnedConceptIDs(parent1.GetConceptID(trans)).Contains(child.getConceptIDNoLock())).To(BeFalse())
			Expect(uOfD.GetConceptsOwnedConceptIDs(parent2.GetConceptID(trans)).Contains(child.getConceptIDNoLock())).To(BeTrue())
		})
	})
	Describe("Test restoration of listeners", func() {
		Specify("When reference deletion is undone/redone", func() {
			target, _ := uOfD.NewElement(trans)
			ref, _ := uOfD.NewReference(trans)
			ref.SetReferencedConcept(target, NoAttribute, trans)
			Expect(uOfD.GetListenerIDs(target.GetConceptID(trans)).Contains(ref.getConceptIDNoLock())).To(BeTrue())
			uOfD.SetRecordingUndo(true)
			uOfD.DeleteElement(ref, trans)
			Expect(uOfD.GetListenerIDs(target.GetConceptID(trans)).Contains(ref.getConceptIDNoLock())).To(BeFalse())
			uOfD.Undo(trans)
			Expect(uOfD.GetListenerIDs(target.GetConceptID(trans)).Contains(ref.getConceptIDNoLock())).To(BeTrue())
			uOfD.Redo(trans)
			Expect(uOfD.GetListenerIDs(target.GetConceptID(trans)).Contains(ref.getConceptIDNoLock())).To(BeFalse())
		})
		Specify("When reference target is changed", func() {
			target1, _ := uOfD.NewElement(trans)
			target2, _ := uOfD.NewElement(trans)
			ref, _ := uOfD.NewReference(trans)
			Expect(ref.SetReferencedConcept(target1, NoAttribute, trans)).To(Succeed())
			Expect(uOfD.GetListenerIDs(target1.GetConceptID(trans)).Contains(ref.getConceptIDNoLock())).To(BeTrue())
			Expect(uOfD.GetListenerIDs(target2.GetConceptID(trans)).Contains(ref.getConceptIDNoLock())).To(BeFalse())
			uOfD.SetRecordingUndo(true)
			Expect(ref.SetReferencedConcept(target2, NoAttribute, trans)).To(Succeed())
			Expect(uOfD.GetListenerIDs(target1.GetConceptID(trans)).Contains(ref.getConceptIDNoLock())).To(BeFalse())
			Expect(uOfD.GetListenerIDs(target2.GetConceptID(trans)).Contains(ref.getConceptIDNoLock())).To(BeTrue())
			uOfD.Undo(trans)
			Expect(uOfD.GetListenerIDs(target1.GetConceptID(trans)).Contains(ref.getConceptIDNoLock())).To(BeTrue())
			Expect(uOfD.GetListenerIDs(target2.GetConceptID(trans)).Contains(ref.getConceptIDNoLock())).To(BeFalse())
			uOfD.Redo(trans)
			Expect(uOfD.GetListenerIDs(target1.GetConceptID(trans)).Contains(ref.getConceptIDNoLock())).To(BeFalse())
			Expect(uOfD.GetListenerIDs(target2.GetConceptID(trans)).Contains(ref.getConceptIDNoLock())).To(BeTrue())
		})
		Specify("When refinement deletion is undone/redone", func() {
			targetA1, _ := uOfD.NewElement(trans)
			targetR1, _ := uOfD.NewElement(trans)
			ref, _ := uOfD.NewRefinement(trans)
			ref.SetAbstractConcept(targetA1, trans)
			ref.SetRefinedConcept(targetR1, trans)
			Expect(uOfD.GetListenerIDs(targetA1.GetConceptID(trans)).Contains(ref.getConceptIDNoLock())).To(BeTrue())
			Expect(uOfD.GetListenerIDs(targetR1.GetConceptID(trans)).Contains(ref.getConceptIDNoLock())).To(BeTrue())
			uOfD.SetRecordingUndo(true)
			uOfD.DeleteElement(ref, trans)
			Expect(uOfD.GetListenerIDs(targetA1.GetConceptID(trans)).Contains(ref.getConceptIDNoLock())).To(BeFalse())
			Expect(uOfD.GetListenerIDs(targetR1.GetConceptID(trans)).Contains(ref.getConceptIDNoLock())).To(BeFalse())
			uOfD.Undo(trans)
			Expect(uOfD.GetListenerIDs(targetA1.GetConceptID(trans)).Contains(ref.getConceptIDNoLock())).To(BeTrue())
			Expect(uOfD.GetListenerIDs(targetR1.GetConceptID(trans)).Contains(ref.getConceptIDNoLock())).To(BeTrue())
			uOfD.Redo(trans)
			Expect(uOfD.GetListenerIDs(targetA1.GetConceptID(trans)).Contains(ref.getConceptIDNoLock())).To(BeFalse())
			Expect(uOfD.GetListenerIDs(targetR1.GetConceptID(trans)).Contains(ref.getConceptIDNoLock())).To(BeFalse())
		})
		Specify("When refinement targets are changed", func() {
			targetA1, _ := uOfD.NewElement(trans)
			targetR1, _ := uOfD.NewElement(trans)
			targetA2, _ := uOfD.NewElement(trans)
			targetR2, _ := uOfD.NewElement(trans)
			ref, _ := uOfD.NewRefinement(trans)
			ref.SetAbstractConcept(targetA1, trans)
			ref.SetRefinedConcept(targetR1, trans)
			Expect(uOfD.GetListenerIDs(targetA1.GetConceptID(trans)).Contains(ref.getConceptIDNoLock())).To(BeTrue())
			Expect(uOfD.GetListenerIDs(targetA2.GetConceptID(trans)).Contains(ref.getConceptIDNoLock())).To(BeFalse())
			uOfD.SetRecordingUndo(true)
			ref.SetAbstractConcept(targetA2, trans)
			Expect(uOfD.GetListenerIDs(targetA1.GetConceptID(trans)).Contains(ref.getConceptIDNoLock())).To(BeFalse())
			Expect(uOfD.GetListenerIDs(targetA2.GetConceptID(trans)).Contains(ref.getConceptIDNoLock())).To(BeTrue())
			uOfD.Undo(trans)
			Expect(uOfD.GetListenerIDs(targetA1.GetConceptID(trans)).Contains(ref.getConceptIDNoLock())).To(BeTrue())
			Expect(uOfD.GetListenerIDs(targetA2.GetConceptID(trans)).Contains(ref.getConceptIDNoLock())).To(BeFalse())
			uOfD.Redo(trans)
			Expect(uOfD.GetListenerIDs(targetA1.GetConceptID(trans)).Contains(ref.getConceptIDNoLock())).To(BeFalse())
			Expect(uOfD.GetListenerIDs(targetA2.GetConceptID(trans)).Contains(ref.getConceptIDNoLock())).To(BeTrue())
			Expect(uOfD.GetListenerIDs(targetR1.GetConceptID(trans)).Contains(ref.getConceptIDNoLock())).To(BeTrue())
			Expect(uOfD.GetListenerIDs(targetR2.GetConceptID(trans)).Contains(ref.getConceptIDNoLock())).To(BeFalse())
			ref.SetRefinedConcept(targetR2, trans)
			Expect(uOfD.GetListenerIDs(targetR1.GetConceptID(trans)).Contains(ref.getConceptIDNoLock())).To(BeFalse())
			Expect(uOfD.GetListenerIDs(targetR2.GetConceptID(trans)).Contains(ref.getConceptIDNoLock())).To(BeTrue())
			uOfD.Undo(trans)
			Expect(uOfD.GetListenerIDs(targetR1.GetConceptID(trans)).Contains(ref.getConceptIDNoLock())).To(BeTrue())
			Expect(uOfD.GetListenerIDs(targetR2.GetConceptID(trans)).Contains(ref.getConceptIDNoLock())).To(BeFalse())
			uOfD.Redo(trans)
			Expect(uOfD.GetListenerIDs(targetR1.GetConceptID(trans)).Contains(ref.getConceptIDNoLock())).To(BeFalse())
			Expect(uOfD.GetListenerIDs(targetR2.GetConceptID(trans)).Contains(ref.getConceptIDNoLock())).To(BeTrue())
		})
	})
	Describe("Test restoration of uriUUIDMap", func() {
		Specify("When element deletion is undone/redone", func() {
			el, _ := uOfD.NewElement(trans)
			uri1 := "http://activeCRL.com/test1"
			el.SetURI(uri1, trans)
			uOfD.SetRecordingUndo(true)
			Expect(uOfD.GetElementWithURI(uri1)).To(Equal(el))
			uOfD.DeleteElement(el, trans)
			Expect(uOfD.GetElementWithURI(uri1)).To(BeNil())
			uOfD.Undo(trans)
			Expect(uOfD.GetElementWithURI(uri1)).To(Equal(el))
			uOfD.Redo(trans)
			Expect(uOfD.GetElementWithURI(uri1)).To(BeNil())
		})
		Specify("When the uri is changed", func() {
			el, _ := uOfD.NewElement(trans)
			uri1 := "http://activeCRL.com/test1"
			uri2 := "http://activeCRL.com/test2"
			el.SetURI(uri1, trans)
			uOfD.SetRecordingUndo(true)
			Expect(uOfD.GetElementWithURI(uri1)).To(Equal(el))
			Expect(uOfD.GetElementWithURI(uri2)).To(BeNil())
			el.SetURI(uri2, trans)
			Expect(uOfD.GetElementWithURI(uri1)).To(BeNil())
			Expect(uOfD.GetElementWithURI(uri2)).To(Equal(el))
			uOfD.Undo(trans)
			Expect(uOfD.GetElementWithURI(uri1)).To(Equal(el))
			Expect(uOfD.GetElementWithURI(uri2)).To(BeNil())
			uOfD.Redo(trans)
			Expect(uOfD.GetElementWithURI(uri1)).To(BeNil())
			Expect(uOfD.GetElementWithURI(uri2)).To(Equal(el))
		})
		Specify("When element creation is undone/redone", func() {
			uOfD.SetRecordingUndo(true)
			uri1 := "http://activeCRL.com/test1"
			el, _ := uOfD.NewElement(trans, uri1)
			Expect(uOfD.GetElementWithURI(uri1)).To(Equal(el))
			uOfD.Undo(trans)
			Expect(uOfD.GetElementWithURI(uri1)).To(BeNil())
			uOfD.Redo(trans)
			Expect(uOfD.GetElementWithURI(uri1)).To(Equal(el))
		})
	})
})
