package crldiagramdomain

import (
	. "github.com/onsi/ginkgo/v2/dsl/core"
	. "github.com/onsi/gomega"
	"github.com/pbrown12303/activeCRL/core"
	"golang.org/x/image/math/fixed"
)

var _ = Describe("CrlDiagramtest", func() {
	var uOfD *core.UniverseOfDiscourse
	var trans *core.Transaction

	BeforeEach(func() {
		uOfD = core.NewUniverseOfDiscourse()
		trans = uOfD.NewTransaction()
		builtCrlDiagramDomain := BuildCrlDiagramDomain(uOfD, trans)
		Expect(builtCrlDiagramDomain).ToNot(BeNil())
		Expect(builtCrlDiagramDomain.GetURI(trans)).To(Equal(CrlDiagramDomainURI))
		Expect(uOfD.GetElementWithURI(CrlDiagramDomainURI)).To(Equal(builtCrlDiagramDomain))
	})

	AfterEach(func() {
		trans.ReleaseLocks()
	})

	Describe("TestBuildCrlDiagramDomain", func() {
		Specify("CrlDiagram should build correctly", func() {
			builtCrlDiagramDomain := uOfD.GetElementWithURI(CrlDiagramDomainURI)
			definingDiagram := builtCrlDiagramDomain.GetFirstOwnedConceptWithURI(CrlDiagramURI, trans)
			crlDiagramWidth := definingDiagram.GetFirstOwnedLiteralWithURI(CrlDiagramWidthURI, trans)
			Expect(crlDiagramWidth).ToNot(BeNil())
			crlDiagramHeight := definingDiagram.GetFirstOwnedLiteralWithURI(CrlDiagramHeightURI, trans)
			Expect(crlDiagramHeight).ToNot(BeNil())
		})

		Specify("CrlDiagramElement should build correctly", func() {
			builtCrlDiagramDomain := uOfD.GetElementWithURI(CrlDiagramDomainURI)
			definingDiagramElement := builtCrlDiagramDomain.GetFirstOwnedConceptWithURI(CrlDiagramElementURI, trans)
			crlDiagramElementModelReference := definingDiagramElement.GetFirstOwnedReferenceWithURI(CrlDiagramElementModelReferenceURI, trans)
			Expect(crlDiagramElementModelReference).ToNot(BeNil())
			crlDiagramElementAbstractionDisplayLabel := definingDiagramElement.GetFirstOwnedLiteralWithURI(CrlDiagramElementAbstractionDisplayLabelURI, trans)
			Expect(crlDiagramElementAbstractionDisplayLabel).ToNot(BeNil())
			crlDiagramElementDisplayLabel := definingDiagramElement.GetFirstOwnedLiteralWithURI(CrlDiagramElementDisplayLabelURI, trans)
			Expect(crlDiagramElementDisplayLabel).ToNot(BeNil())
		})

		Specify("CrlDiagramNode should build correctly", func() {
			builtCrlDiagramDomain := uOfD.GetElementWithURI(CrlDiagramDomainURI)
			definingDiagramNode := builtCrlDiagramDomain.GetFirstOwnedConceptWithURI(CrlDiagramNodeURI, trans)
			crlDiagramNodeX := definingDiagramNode.GetFirstOwnedLiteralWithURI(CrlDiagramNodeXURI, trans)
			Expect(crlDiagramNodeX).ToNot(BeNil())
			crlDiagramNodeY := definingDiagramNode.GetFirstOwnedLiteralWithURI(CrlDiagramNodeYURI, trans)
			Expect(crlDiagramNodeY).ToNot(BeNil())
			crlDiagramNodeHeight := definingDiagramNode.GetFirstOwnedLiteralWithURI(CrlDiagramNodeHeightURI, trans)
			Expect(crlDiagramNodeHeight).ToNot(BeNil())
			crlDiagramNodeWidth := definingDiagramNode.GetFirstOwnedLiteralWithURI(CrlDiagramNodeWidthURI, trans)
			Expect(crlDiagramNodeWidth).ToNot(BeNil())
		})

		Specify("CrlDiagramLink should build correctly", func() {
			builtCrlDiagramDomain := uOfD.GetElementWithURI(CrlDiagramDomainURI)
			crlDiagramLink := builtCrlDiagramDomain.GetFirstOwnedConceptWithURI(CrlDiagramLinkURI, trans)
			Expect(crlDiagramLink).ToNot(BeNil())
			crlDiagramLinkSourceReference := crlDiagramLink.GetFirstOwnedReferenceWithURI(CrlDiagramLinkSourceURI, trans)
			Expect(crlDiagramLinkSourceReference).ToNot(BeNil())
			crlDiagramLinkTargetReference := crlDiagramLink.GetFirstOwnedReferenceWithURI(CrlDiagramLinkSourceURI, trans)
			Expect(crlDiagramLinkTargetReference).ToNot(BeNil())
		})

		Specify("CrlDiagramPointer and refinements should build correctly", func() {
			builtCrlDiagramDomain := uOfD.GetElementWithURI(CrlDiagramDomainURI)
			crlPointer := builtCrlDiagramDomain.GetFirstOwnedConceptWithURI(CrlDiagramPointerURI, trans)
			Expect(crlPointer).ToNot(BeNil())
			crlOwnerPointer := builtCrlDiagramDomain.GetFirstOwnedConceptWithURI(CrlDiagramOwnerPointerURI, trans)
			Expect(crlOwnerPointer).ToNot(BeNil())
			Expect(crlOwnerPointer.IsRefinementOf(crlPointer, trans)).To(BeTrue())
			crlAbstractPointer := builtCrlDiagramDomain.GetFirstOwnedConceptWithURI(CrlDiagramAbstractPointerURI, trans)
			Expect(crlAbstractPointer).ToNot(BeNil())
			Expect(crlAbstractPointer.IsRefinementOf(crlPointer, trans)).To(BeTrue())
			crlRefinedPointer := builtCrlDiagramDomain.GetFirstOwnedConceptWithURI(CrlDiagramRefinedPointerURI, trans)
			Expect(crlRefinedPointer).ToNot(BeNil())
			Expect(crlRefinedPointer.IsRefinementOf(crlPointer, trans)).To(BeTrue())
			crlElementPointer := builtCrlDiagramDomain.GetFirstOwnedConceptWithURI(CrlDiagramElementPointerURI, trans)
			Expect(crlElementPointer).ToNot(BeNil())
			Expect(crlElementPointer.IsRefinementOf(crlPointer, trans)).To(BeTrue())
		})
	})
	Describe("Test convenience functions", func() {
		Specify("GetReferencedElement and SetReferencedElement should work", func() {
			node, _ := NewDiagramNode(trans)
			target, _ := uOfD.NewElement(trans)
			SetReferencedModelConcept(node, target, trans)
			Expect(GetReferencedModelConcept(node, trans)).To(Equal(target))
			Expect(node.GetFirstOwnedReferenceRefinedFromURI(CrlDiagramElementModelReferenceURI, trans)).ToNot(BeNil())
			Expect(node.GetFirstOwnedReferenceRefinedFromURI(CrlDiagramElementModelReferenceURI, trans).GetReferencedConcept(trans)).To(Equal(target))
		})
		Specify("SetReferencedElement should gracefully handle a nil argument", func() {
			target, _ := uOfD.NewElement(trans)
			SetReferencedModelConcept(nil, target, trans)
		})
		Specify("SetReferencedElement should gracefully handle a nil argument", func() {
			node, _ := NewDiagramNode(trans)
			SetReferencedModelConcept(node, nil, trans)
		})
		Specify("Test GetAbstractionDisplayLabel and SetAbstractionDisplayLabel", func() {
			node, _ := NewDiagramNode(trans)
			displayLabel := "displayLabel"
			SetAbstractionDisplayLabel(node, displayLabel, trans)
			Expect(GetAbstractionDisplayLabel(node, trans)).To(Equal(displayLabel))
		})
		Specify("Test GetDisplayLabel and SetDisplayLabel", func() {
			node, _ := NewDiagramNode(trans)
			displayLabel := "displayLabel"
			SetDisplayLabel(node, displayLabel, trans)
			Expect(GetDisplayLabel(node, trans)).To(Equal(displayLabel))
		})
		Specify("Test GetNodeHeight and SetNodeHeight", func() {
			node, _ := NewDiagramNode(trans)
			value := 123.45
			SetNodeHeight(node, value, trans)
			Expect(GetNodeHeight(node, trans)).To(Equal(value))
		})
		Specify("Test GetNodeWidth and SetNodeWidth", func() {
			node, _ := NewDiagramNode(trans)
			value := 123.45
			SetNodeWidth(node, value, trans)
			Expect(GetNodeWidth(node, trans)).To(Equal(value))
		})
		Specify("Test GetNodeX and SetNodeX", func() {
			node, _ := NewDiagramNode(trans)
			value := 123.45
			SetNodeX(node, value, trans)
			Expect(GetNodeX(node, trans)).To(Equal(value))
		})
		Specify("Test GetNodeY and SetNodeY", func() {
			node, _ := NewDiagramNode(trans)
			value := 123.45
			SetNodeY(node, value, trans)
			Expect(GetNodeY(node, trans)).To(Equal(value))
		})
		Specify("GetLinkSource and SetLinkSource should work", func() {
			link, _ := NewDiagramReferenceLink(trans)
			target, _ := uOfD.NewElement(trans)
			SetLinkSource(link, target, trans)
			Expect(GetLinkSource(link, trans)).To(Equal(target))
			Expect(link.GetFirstOwnedReferenceRefinedFromURI(CrlDiagramLinkSourceURI, trans)).ToNot(BeNil())
			Expect(link.GetFirstOwnedReferenceRefinedFromURI(CrlDiagramLinkSourceURI, trans).GetReferencedConcept(trans)).To(Equal(target))
		})
		Specify("GetLinkTarget and SetLinkTarget should work", func() {
			link, _ := NewDiagramReferenceLink(trans)
			target, _ := uOfD.NewElement(trans)
			SetLinkTarget(link, target, trans)
			Expect(GetLinkTarget(link, trans)).To(Equal(target))
			Expect(link.GetFirstOwnedReferenceRefinedFromURI(CrlDiagramLinkTargetURI, trans)).ToNot(BeNil())
			Expect(link.GetFirstOwnedReferenceRefinedFromURI(CrlDiagramLinkTargetURI, trans).GetReferencedConcept(trans)).To(Equal(target))
		})
	})
	Describe("Test Fixed-to-Float conversions", func() {
		Specify("Zero should equal zero", func() {
			fixedX := fixed.I(0)
			floatX := Int26_6ToFloat(fixedX)
			Expect(floatX).To(Equal(0.0))
		})
		Specify("One should equal one", func() {
			fixedX := fixed.I(1)
			floatX := Int26_6ToFloat(fixedX)
			Expect(floatX).To(Equal(1.0))
		})
		Specify("Minus One should equal minus one", func() {
			fixedX := fixed.I(-1)
			floatX := Int26_6ToFloat(fixedX)
			Expect(floatX).To(Equal(-1.0))
		})
		Specify("0.5 should equal 0.5", func() {
			var fixedX fixed.Int26_6 = 1 << 5
			floatX := Int26_6ToFloat(fixedX)
			Expect(floatX).To(Equal(0.5))
		})
	})

	Describe("Test New... functions", func() {
		BeforeEach(func() {
			BuildCrlDiagramDomain(uOfD, trans)
		})
		Specify("Createing a new diagram should work", func() {
			newDiagram, err := NewDiagram(trans)
			Expect(err).To(BeNil())
			Expect(newDiagram).ToNot(BeNil())
			Expect(newDiagram.IsRefinementOfURI(CrlDiagramURI, trans)).To(BeTrue())
			crlDiagramWidth := newDiagram.GetFirstOwnedLiteralRefinedFromURI(CrlDiagramWidthURI, trans)
			Expect(crlDiagramWidth).ToNot(BeNil())
			crlDiagramHeight := newDiagram.GetFirstOwnedLiteralRefinedFromURI(CrlDiagramHeightURI, trans)
			Expect(crlDiagramHeight).ToNot(BeNil())

		})
		Specify("Creating a new node shoud work", func() {
			newDiagramNode, err := NewDiagramNode(trans)
			Expect(err).To(BeNil())
			Expect(newDiagramNode).ToNot(BeNil())
			Expect(newDiagramNode.IsRefinementOfURI(CrlDiagramNodeURI, trans)).To(BeTrue())
			Expect(newDiagramNode.IsRefinementOfURI(CrlDiagramNodeURI, trans)).To(BeTrue())
			crlDiagramElementModelReference := newDiagramNode.GetFirstOwnedReferenceRefinedFromURI(CrlDiagramElementModelReferenceURI, trans)
			Expect(crlDiagramElementModelReference).ToNot(BeNil())
			crlDiagramElementAbstractionDisplayLabel := newDiagramNode.GetFirstOwnedLiteralRefinedFromURI(CrlDiagramElementAbstractionDisplayLabelURI, trans)
			Expect(crlDiagramElementAbstractionDisplayLabel).ToNot(BeNil())
			crlDiagramElementDisplayLabel := newDiagramNode.GetFirstOwnedLiteralRefinedFromURI(CrlDiagramElementDisplayLabelURI, trans)
			Expect(crlDiagramElementDisplayLabel).ToNot(BeNil())
			crlDiagramNodeX := newDiagramNode.GetFirstOwnedLiteralRefinedFromURI(CrlDiagramNodeXURI, trans)
			Expect(crlDiagramNodeX).ToNot(BeNil())
			crlDiagramNodeY := newDiagramNode.GetFirstOwnedLiteralRefinedFromURI(CrlDiagramNodeYURI, trans)
			Expect(crlDiagramNodeY).ToNot(BeNil())
			crlDiagramNodeHeight := newDiagramNode.GetFirstOwnedLiteralRefinedFromURI(CrlDiagramNodeHeightURI, trans)
			Expect(crlDiagramNodeHeight).ToNot(BeNil())
			crlDiagramNodeWidth := newDiagramNode.GetFirstOwnedLiteralRefinedFromURI(CrlDiagramNodeWidthURI, trans)
			Expect(crlDiagramNodeWidth).ToNot(BeNil())
		})
		Specify("Creating a new reference link shoud work", func() {
			link, err := NewDiagramReferenceLink(trans)
			Expect(err).To(BeNil())
			Expect(link).ToNot(BeNil())
			Expect(link.IsRefinementOfURI(CrlDiagramReferenceLinkURI, trans)).To(BeTrue())
			crlDiagramElementModelReference := link.GetFirstOwnedReferenceRefinedFromURI(CrlDiagramElementModelReferenceURI, trans)
			Expect(crlDiagramElementModelReference).ToNot(BeNil())
			crlDiagramLinkAbstractionDisplayLabel := link.GetFirstOwnedLiteralRefinedFromURI(CrlDiagramLinkAbstractionDisplayLabelURI, trans)
			Expect(crlDiagramLinkAbstractionDisplayLabel).ToNot(BeNil())
			ValidateAnchoredText(crlDiagramLinkAbstractionDisplayLabel, trans)
			crlDiagramLinkDisplayLabel := link.GetFirstOwnedLiteralRefinedFromURI(CrlDiagramLinkDisplayLabelURI, trans)
			Expect(crlDiagramLinkDisplayLabel).ToNot(BeNil())
			ValidateAnchoredText(crlDiagramLinkDisplayLabel, trans)
			crlDiagramLinkSourceReference := link.GetFirstOwnedReferenceRefinedFromURI(CrlDiagramLinkSourceURI, trans)
			Expect(crlDiagramLinkSourceReference).ToNot(BeNil())
			crlDiagramLinkTargetReference := link.GetFirstOwnedReferenceRefinedFromURI(CrlDiagramLinkSourceURI, trans)
			Expect(crlDiagramLinkTargetReference).ToNot(BeNil())
			multiplicity := link.GetFirstOwnedConceptRefinedFromURI(CrlDiagramLinkMultiplicityURI, trans)
			Expect(multiplicity).ToNot(BeNil())
			ValidateAnchoredText(multiplicity, trans)
		})
		Specify("Creating a new refinement link shoud work", func() {
			link, err := NewDiagramRefinementLink(trans)
			Expect(err).To(BeNil())
			Expect(link).ToNot(BeNil())
			Expect(link.IsRefinementOfURI(CrlDiagramRefinementLinkURI, trans)).To(BeTrue())
			crlDiagramElementModelReference := link.GetFirstOwnedReferenceRefinedFromURI(CrlDiagramElementModelReferenceURI, trans)
			Expect(crlDiagramElementModelReference).ToNot(BeNil())
			crlDiagramLinkAbstractionDisplayLabel := link.GetFirstOwnedLiteralRefinedFromURI(CrlDiagramLinkAbstractionDisplayLabelURI, trans)
			Expect(crlDiagramLinkAbstractionDisplayLabel).ToNot(BeNil())
			ValidateAnchoredText(crlDiagramLinkAbstractionDisplayLabel, trans)
			crlDiagramLinkDisplayLabel := link.GetFirstOwnedLiteralRefinedFromURI(CrlDiagramLinkDisplayLabelURI, trans)
			Expect(crlDiagramLinkDisplayLabel).ToNot(BeNil())
			ValidateAnchoredText(crlDiagramLinkDisplayLabel, trans)
			Expect(link.IsRefinementOfURI(CrlDiagramRefinementLinkURI, trans)).To(BeTrue())
			crlDiagramLinkSourceReference := link.GetFirstOwnedReferenceRefinedFromURI(CrlDiagramLinkSourceURI, trans)
			Expect(crlDiagramLinkSourceReference).ToNot(BeNil())
			crlDiagramLinkTargetReference := link.GetFirstOwnedReferenceRefinedFromURI(CrlDiagramLinkSourceURI, trans)
			Expect(crlDiagramLinkTargetReference).ToNot(BeNil())
		})
		Specify("Creating a new ownerPointer shoud work", func() {
			ownerPointer, err := NewDiagramOwnerPointer(trans)
			Expect(err).To(BeNil())
			Expect(ownerPointer).ToNot(BeNil())
			Expect(ownerPointer.IsRefinementOfURI(CrlDiagramOwnerPointerURI, trans)).To(BeTrue())
			crlDiagramElementModelReference := ownerPointer.GetFirstOwnedReferenceRefinedFromURI(CrlDiagramElementModelReferenceURI, trans)
			Expect(crlDiagramElementModelReference).ToNot(BeNil())
			crlDiagramLinkAbstractionDisplayLabel := ownerPointer.GetFirstOwnedLiteralRefinedFromURI(CrlDiagramLinkAbstractionDisplayLabelURI, trans)
			Expect(crlDiagramLinkAbstractionDisplayLabel).ToNot(BeNil())
			ValidateAnchoredText(crlDiagramLinkAbstractionDisplayLabel, trans)
			crlDiagramLinkDisplayLabel := ownerPointer.GetFirstOwnedLiteralRefinedFromURI(CrlDiagramLinkDisplayLabelURI, trans)
			Expect(crlDiagramLinkDisplayLabel).ToNot(BeNil())
			ValidateAnchoredText(crlDiagramLinkDisplayLabel, trans)
			crlDiagramLinkSourceReference := ownerPointer.GetFirstOwnedReferenceRefinedFromURI(CrlDiagramLinkSourceURI, trans)
			Expect(crlDiagramLinkSourceReference).ToNot(BeNil())
			crlDiagramLinkTargetReference := ownerPointer.GetFirstOwnedReferenceRefinedFromURI(CrlDiagramLinkSourceURI, trans)
			Expect(crlDiagramLinkTargetReference).ToNot(BeNil())
			multiplicity := ownerPointer.GetFirstOwnedConceptRefinedFromURI(CrlDiagramLinkMultiplicityURI, trans)
			Expect(multiplicity).ToNot(BeNil())
			ValidateAnchoredText(multiplicity, trans)
		})
		Specify("Creating a new elementPointer shoud work", func() {
			elementPointer, err := NewDiagramElementPointer(trans)
			Expect(err).To(BeNil())
			Expect(elementPointer).ToNot(BeNil())
			Expect(elementPointer.IsRefinementOfURI(CrlDiagramElementPointerURI, trans)).To(BeTrue())
			crlDiagramElementModelReference := elementPointer.GetFirstOwnedReferenceRefinedFromURI(CrlDiagramElementModelReferenceURI, trans)
			Expect(crlDiagramElementModelReference).ToNot(BeNil())
			crlDiagramLinkAbstractionDisplayLabel := elementPointer.GetFirstOwnedLiteralRefinedFromURI(CrlDiagramLinkAbstractionDisplayLabelURI, trans)
			Expect(crlDiagramLinkAbstractionDisplayLabel).ToNot(BeNil())
			ValidateAnchoredText(crlDiagramLinkAbstractionDisplayLabel, trans)
			crlDiagramLinkDisplayLabel := elementPointer.GetFirstOwnedLiteralRefinedFromURI(CrlDiagramLinkDisplayLabelURI, trans)
			Expect(crlDiagramLinkDisplayLabel).ToNot(BeNil())
			ValidateAnchoredText(crlDiagramLinkDisplayLabel, trans)
			crlDiagramLinkSourceReference := elementPointer.GetFirstOwnedReferenceRefinedFromURI(CrlDiagramLinkSourceURI, trans)
			Expect(crlDiagramLinkSourceReference).ToNot(BeNil())
			crlDiagramLinkTargetReference := elementPointer.GetFirstOwnedReferenceRefinedFromURI(CrlDiagramLinkSourceURI, trans)
			Expect(crlDiagramLinkTargetReference).ToNot(BeNil())
		})
		Specify("Creating a new abstractPointer shoud work", func() {
			abstractPointer, err := NewDiagramAbstractPointer(trans)
			Expect(err).To(BeNil())
			Expect(abstractPointer).ToNot(BeNil())
			Expect(abstractPointer.IsRefinementOfURI(CrlDiagramAbstractPointerURI, trans)).To(BeTrue())
			crlDiagramElementModelReference := abstractPointer.GetFirstOwnedReferenceRefinedFromURI(CrlDiagramElementModelReferenceURI, trans)
			Expect(crlDiagramElementModelReference).ToNot(BeNil())
			crlDiagramLinkAbstractionDisplayLabel := abstractPointer.GetFirstOwnedLiteralRefinedFromURI(CrlDiagramLinkAbstractionDisplayLabelURI, trans)
			Expect(crlDiagramLinkAbstractionDisplayLabel).ToNot(BeNil())
			ValidateAnchoredText(crlDiagramLinkAbstractionDisplayLabel, trans)
			crlDiagramLinkDisplayLabel := abstractPointer.GetFirstOwnedLiteralRefinedFromURI(CrlDiagramLinkDisplayLabelURI, trans)
			Expect(crlDiagramLinkDisplayLabel).ToNot(BeNil())
			ValidateAnchoredText(crlDiagramLinkDisplayLabel, trans)
			crlDiagramLinkSourceReference := abstractPointer.GetFirstOwnedReferenceRefinedFromURI(CrlDiagramLinkSourceURI, trans)
			Expect(crlDiagramLinkSourceReference).ToNot(BeNil())
			crlDiagramLinkTargetReference := abstractPointer.GetFirstOwnedReferenceRefinedFromURI(CrlDiagramLinkSourceURI, trans)
			Expect(crlDiagramLinkTargetReference).ToNot(BeNil())
		})
		Specify("Creating a new refinedPointer shoud work", func() {
			refinedPointer, err := NewDiagramRefinedPointer(trans)
			Expect(err).To(BeNil())
			Expect(refinedPointer).ToNot(BeNil())
			Expect(refinedPointer.IsRefinementOfURI(CrlDiagramRefinedPointerURI, trans)).To(BeTrue())
			crlDiagramElementModelReference := refinedPointer.GetFirstOwnedReferenceRefinedFromURI(CrlDiagramElementModelReferenceURI, trans)
			Expect(crlDiagramElementModelReference).ToNot(BeNil())
			crlDiagramLinkAbstractionDisplayLabel := refinedPointer.GetFirstOwnedLiteralRefinedFromURI(CrlDiagramLinkAbstractionDisplayLabelURI, trans)
			Expect(crlDiagramLinkAbstractionDisplayLabel).ToNot(BeNil())
			ValidateAnchoredText(crlDiagramLinkAbstractionDisplayLabel, trans)
			crlDiagramLinkDisplayLabel := refinedPointer.GetFirstOwnedLiteralRefinedFromURI(CrlDiagramLinkDisplayLabelURI, trans)
			Expect(crlDiagramLinkDisplayLabel).ToNot(BeNil())
			ValidateAnchoredText(crlDiagramLinkDisplayLabel, trans)
			crlDiagramLinkSourceReference := refinedPointer.GetFirstOwnedReferenceRefinedFromURI(CrlDiagramLinkSourceURI, trans)
			Expect(crlDiagramLinkSourceReference).ToNot(BeNil())
			crlDiagramLinkTargetReference := refinedPointer.GetFirstOwnedReferenceRefinedFromURI(CrlDiagramLinkSourceURI, trans)
			Expect(crlDiagramLinkTargetReference).ToNot(BeNil())
		})
	})
})

func ValidateAnchoredText(anchoredText core.Concept, trans *core.Transaction) {
	anchorX := anchoredText.GetFirstOwnedConceptRefinedFromURI(CrlDiagramAnchoredTextAnchorXURI, trans)
	Expect(anchorX).ToNot(BeNil())
	anchorY := anchoredText.GetFirstOwnedConceptRefinedFromURI(CrlDiagramAnchoredTextAnchorYURI, trans)
	Expect(anchorY).ToNot(BeNil())
	offsetX := anchoredText.GetFirstOwnedConceptRefinedFromURI(CrlDiagramAnchoredTextOffsetXURI, trans)
	Expect(offsetX).ToNot(BeNil())
	offsetY := anchoredText.GetFirstOwnedConceptRefinedFromURI(CrlDiagramAnchoredTextOffsetYURI, trans)
	Expect(offsetY).ToNot(BeNil())
	visible := anchoredText.GetFirstOwnedConceptRefinedFromURI(CrlDiagramAnchoredTextVisibleURI, trans)
	Expect(visible).ToNot(BeNil())
}
